# Generated by Django 2.0 on 2018-01-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpollprofile',
            old_name='vote_date',
            new_name='poll_date',
        ),
    ]
