# Generated by Django 2.0 on 2018-01-25 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamstats', '0002_auto_20180118_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPollProfile',
            new_name='PollProfile',
        ),
    ]
