# Generated by Django 2.0 on 2018-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0003_auto_20180125_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollprofile',
            name='poll_date',
            field=models.DateField(auto_now=True),
        ),
    ]
